core/urls.py
from django.urls import path, include
from .views import (
    ItemDetailView, ItemView, checkout,
    view_404,
    itemview,
    add_to_cart,
    OrderSummaryView,
    ShopView,
    remove_from_cart,
    shop_product,
    remove_single_item_from_cart,
    AddCouponView,
    CheckoutView,
    switch_to_Ukraiunian_link,
    switch_to_English_link,
    deliveryAndPayPage,
    switch_to_Russian_link,   
)

app_name = 'core'

urlpatterns = [
    # path('', home_view, name='home-view'),
    path('uk/', switch_to_Ukraiunian_link, name='uk'),
    path('en/', switch_to_English_link, name='en'),
    path('ru/', switch_to_Russian_link, name='ru'),
    path('', itemview, name='menu'),
    path('delivery/', deliveryAndPayPage, name='delivery'),
    path('shop/', ShopView.as_view(), name='shop'),
    path('shop/<str:slug>', shop_product, name='shop-product'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('item/<slug>', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>', remove_from_cart, name='remove-from-cart'),
    path('404/', view_404, name='404-view'),
    # path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('order-summary/', OrderSummaryView, name='order-summary'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add_coupon'),
]

propositions/urls.py
from django.urls import path, include
from .views import PropositionsView, PropositionsViewDetailView

app_name = 'proposition'


urlpatterns = [
    path('', PropositionsView.as_view(), name='all_prospositions'),
    path('single_proposition/<slug>', PropositionsViewDetailView.as_view(), name='single_proposition'),
]

tokyotest/urls.py
from typing import Pattern
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve
from django.urls import re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('proposition/', include('propositions.urls')),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% extends "main.html" %}
{% load static %}
{% block main_body %}

{% include "loader.html" %}
        <!-- loader end  -->
        <!-- main start  -->
            <!-- header  -->
            {% include "header.html" %}

    <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>

    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}

    {% include "footer.html" %}

    {% endblock main_body %}

templates/blog-single.html
{% extends "main.html" %} {% block main_body %} {% load static %}
<!-- lodaer  -->
{% include "loader.html" %} {% load l10n %}
<!-- loader end  -->
<!-- main start  -->
<div id="main">
    <!-- header  -->
    {% include "header.html" %}
    <!-- header  -->
    <!--header end -->
    <!-- wrapper  -->
    <div id="wrapper">
        <!-- content  -->
        <div class="content">
            <!--  section  -->
            <section class="parallax-section hero-section hidden-section" data-scrollax-parent="true">
                <div class="bg par-elem" data-bg="{% static 'images/bg/1.jpg' %}" data-scrollax="properties: { translateY: '30%' }"></div>
                <div class="overlay"></div>
                <div class="container">
                    <div class="section-title">
                        <h2>{% if request.session.lang == "uk" %} Акції {% elif request.session.lang == "ru" %} Акции {% else %} Promotions {% endif %}</h2>
                        <!-- <h2>Our Journal</h2> -->
                        <div class="dots-separator fl-wrap"><span></span></div>
                    </div>
                </div>
                <div class="hero-section-scroll">
                    <div class="mousey">
                        <div class="scroller"></div>
                    </div>
                </div>
                <div class="brush-dec"></div>
            </section>
            <!--  section  end-->
            <!--  section  -->
            <section class="hidden-section">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="fl-wrap post-container">
                                <!-- post -->
                                {% if request.session.lang == "uk" %}
                                <div class="post fl-wrap fw-post">
                                    <h2><a href="{{ post.get_absolute_url }}">{{ object.title }}</a></h2>
                                    <ul class="blog-title-opt">
                                        <li><a href="#">{{ object.date_added|date:"SHORT_DATE_FORMAT" }}</a></li>
                                    </ul>
                                    <!-- blog media -->
                                    <div class="blog-media fl-wrap">
                                        <div class="single-slider-wrap">
                                            <div class="single-slider fl-wrap">
                                                <div class="swiper-container">
                                                    <div class="swiper-wrapper lightgallery">
                                                        <div class="swiper-slide hov_zoom">
                                                            <img src="{{ object.proposition_photo.url }}" alt="" /><a href="{{ object.proposition_photo.url }}" class="box-media-zoom popup-image"><i class="fal fa-search"></i></a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- blog media end -->
                                    <div class="blog-text fl-wrap">
                                        <div class="pr-tags fl-wrap">
                                            <span>Теги : </span>
                                            <ul>
                                                {% for category in object.tag.all %}
                                                <li><a href="#"> {{ category.tag_name }} </a></li>
                                                {% endfor %}
                                            </ul>
                                        </div>
                                        {{ object.description|safe }}
                                    </div>
                                </div>
                                {% elif request.session.lang == "ru" %}
                                <div class="post fl-wrap fw-post">
                                    <h2><a href="{{ post.get_absolute_url }}">{{ object.title_ru }}</a></h2>
                                    <ul class="blog-title-opt">
                                        <li><a href="#">{{ object.date_added|date:"SHORT_DATE_FORMAT" }}</a></li>
                                    </ul>
                                    <!-- blog media -->
                                    <div class="blog-media fl-wrap">
                                        <div class="single-slider-wrap">
                                            <div class="single-slider fl-wrap">
                                                <div class="swiper-container">
                                                    <div class="swiper-wrapper lightgallery">
                                                        <div class="swiper-slide hov_zoom">
                                                            <img src="{{ object.proposition_photo.url }}" alt="" /><a href="{{ object.proposition_photo.url }}" class="box-media-zoom popup-image"><i class="fal fa-search"></i></a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- blog media end -->
                                    <div class="blog-text fl-wrap">
                                        <div class="pr-tags fl-wrap">
                                            <span>Теги : </span>
                                            <ul>
                                                {% for category in object.tag.all %}
                                                <li><a href="#"> {{ category.tag_ru_name }} </a></li>
                                                {% endfor %}
                                            </ul>
                                        </div>
                                        {{ object.description_ru|safe }}
                                    </div>
                                </div>
                                {% else %}
                                <div class="post fl-wrap fw-post">
                                    <h2><a href="{{ post.get_absolute_url }}">{{ object.title_eng }}</a></h2>
                                    <ul class="blog-title-opt">
                                        <li><a href="#">{{ object.date_added|date:"SHORT_DATE_FORMAT" }}</a></li>
                                    </ul>
                                    <!-- blog media -->
                                    <div class="blog-media fl-wrap">
                                        <div class="single-slider-wrap">
                                            <div class="single-slider fl-wrap">
                                                <div class="swiper-container">
                                                    <div class="swiper-wrapper lightgallery">
                                                        <div class="swiper-slide hov_zoom">
                                                            <img src="{{ object.proposition_photo.url }}" alt="" /><a href="{{ object.proposition_photo.url }}" class="box-media-zoom popup-image"><i class="fal fa-search"></i></a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- blog media end -->
                                    <div class="blog-text fl-wrap">
                                        <div class="pr-tags fl-wrap">
                                            <span>Tags : </span>
                                            <ul>
                                                {% for category in object.tag.all %}
                                                <li><a href="#"> {{ category.tag_eng_name }} </a></li>
                                                {% endfor %}
                                            </ul>
                                        </div>
                                        {{ object.description_eng|safe }}
                                    </div>
                                </div>
                                {% endif %}
                                <!-- post end-->
                            </div>
                        </div>
                        <!--  sidebar  -->
                        <!--  sidebar end-->
                    </div>
                    <div class="fl-wrap limit-box"></div>
                </div>
                <div class="section-bg">
                    <div class="bg" data-bg="{% static 'images/bg/dec/section-bg.png' %}"></div>
                </div>
            </section>
            <!--  section end  -->
            <div class="brush-dec2 brush-dec_bottom"></div>
        </div>
        <!-- content end  -->
        <!-- footer -->
        <div class="height-emulator fl-wrap"></div>
        {% include "footer.html" %}
        <!-- footer end-->
    </div>
    <!-- wrapper end -->
    {% include "reservation.html" %}
    <!-- cursor-->
    <div class="element">
        <div class="element-item"></div>
    </div>
    <!-- cursor end-->
</div>
<!-- Main end -->
<!--=============== scripts  ===============-->
{% endblock main_body %}

templates/footer.html
{% load static %}

<footer class="fl-wrap dark-bg fixed-footer">
    <div class="container">
        <div class="footer-top fl-wrap">
            <!-- <a href="{% url 'core:menu' %}" class="footer-logo"><img src='{% static "images/logo.png" %}' alt=""></a> -->
            <div class="lang-wrap"><a href="#" class='uk-lang act-lang'>Uk</a><span>/</span><a class='en-lang' href="#">En</a><span>/</span><a class='ru-lang' href="#">Ru</a></div>
            <div class="footer-social">
                <span class="footer-social-title">
                    {% if request.session.lang == "uk" %}
                        Спостерігати за нами :
                    {% elif request.session.lang == "ru" %}
                        Следить за нами :
                    {% else %}
                        Follow us :
                    {% endif %}
                </span>
                <ul>
                    <li><a href="https://www.facebook.com/tokyo.od.ua/" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
                    <li><a href="https://instagram.com/tokyo.od.ua?igshid=o5y4xnlsjtwo" target="_blank"><i class="fab fa-instagram"></i></a></li>
                </ul>
            </div>
        </div>
        <!-- footer-widget-wrap -->
        <div class="footer-widget-wrap fl-wrap">
            <div class="row">
                <!-- footer-widget -->
                <div class="col-md-4">
                    <div class="footer-widget">
                        <div class="footer-widget-title">
                            {% if request.session.lang == "uk" %}
                                Розділи :
                            {% elif request.session.lang == "ru" %}
                                Разделы :
                            {% else %}
                                Sections :
                            {% endif %}
                        </div>
                        <div class="footer-widget-content">
                            <div class="footer-contacts footer-box fl-wrap">
                                <ul>
                                    <li><a class="footer-widget-title" href="{% url  'core:menu' %}">
                                            {% if request.session.lang == "uk" %}
                                                МЕНЮ
                                            {% elif request.session.lang == "ru" %}
                                                МЕНЮ
                                            {% else %}
                                                MENU
                                            {% endif %}
                                        </a>
                                    </li>
                                    <li><a class="footer-widget-title" href="{% url  'proposition:all_prospositions' %}">
                                        {% if request.session.lang == "uk" %}
                                            АКЦІЇ
                                        {% elif request.session.lang == "ru" %}
                                            АКЦИИ
                                        {% else %}
                                            PROMOTIONS
                                        {% endif %}</a>
                                    </li>
                                    <li><a class="footer-widget-title" href="{% url  'core:shop' %}">
                                        {% if request.session.lang == "uk" %}
                                            ПОШУК ПО КОМПОНЕНТАМ
                                        {% elif request.session.lang == "ru" %}
                                            ПОИСК ПО КОМПОНЕНТАМ
                                        {% else %}
                                            SEARCH BY COMPONENTS
                                        {% endif %}</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- footer-widget  end-->
                <!-- footer-widget -->
                <div class="col-md-4">
                    <div class="footer-widget">
                        <div class="footer-widget-title">
                            {% if request.session.lang == "uk" %}
                                Графік роботи:
                            {% elif request.session.lang == "ru" %}
                                График работы:
                            {% else %}
                                Work schedule: 
                            {% endif %}
                        </div>
                        <div class="footer-widget-content">
                            <div class="footer-contacts footer-box fl-wrap">
                                <ul>
                                    <li>
                                        <span>
                                            {% if request.session.lang == "uk" %}
                                                Пн-Пт :
                                            {% elif request.session.lang == "ru" %}
                                                Пн-Пт :
                                            {% else %}
                                                Mon-Fri from
                                            {% endif %}
                                        </span>
                                        <a href="#">10:00 - 22:30</a>
                                    </li>
                                    <li>
                                        <span>
                                            {% if request.session.lang == "uk" %}
                                                Сб-Нд :
                                            {% elif request.session.lang == "ru" %}
                                                Сб-Вс :
                                            {% else %}
                                                Sat-Sun from
                                            {% endif %}
                                        </span>
                                        <a href="#">10:00 - 22:30</a>
                                    </li>
                                </ul>
                            </div>                            	
                        </div>
                    </div>
                </div>
                <!-- footer-widget  end-->
                <!-- footer-widget -->
                <div class="col-md-4">
                    <div class="footer-widget">
                        <div class="footer-widget-title">{% if request.session.lang == "uk" %}
                            Зателефонувати
                        {% elif request.session.lang == "ru" %}
                            Позвонить
                        {% else %}
                            Call
                        {% endif %}</div>
                        <div class="footer-widget-content">
                            <div class="footer-contacts footer-box fl-wrap">
                                <ul>
                                    <li><a href="tel:+380730484348">+380730484348</a></li>
                                    <li><a href="tel:+380970484348">+380970484348</a></li>
                                </ul>
                            </div>                            	
                        </div>
                    </div>
                </div>
                <!-- footer-widget  end-->
            </div>
        </div>
        <!-- footer-widget-wrap end-->
        <div class="footer-bottom fl-wrap">
            <div class="copyright">&#169; tokyo.od.ua 2021 . All rights reserved. </div>
            <div class="to-top"><span>{% if request.session.lang == "uk" %}
                Перейти до верху
            {% elif request.session.lang == "ru" %}
                Перейти на верх
            {% else %}
                Go to the top 
            {% endif %} </span><i class="fal fa-angle-double-up"></i></div>
        </div>
    </div>
</footer>

templates/header.html
{% load cart_template_tags %} {% load static %}
<header class="main-header">
    <!-- header-top  -->
    <div class="header-top">
        <div class="container">
            <!-- <div class="lang-wrap"><a href="#" class="act-lang">En</a><span>/</span><a href="#">Fr</a></div> -->
            <div class="header-top_contacts">
                <a href="tel:+380941675843"><span>{% if request.session.lang == "uk" %} Подзвонити{% elif request.session.lang == "ru" %}Позвонить {% else %} Call {% endif %}:</span> +38(094)-167-58-43</a><a href="mailto:tokyo.od.ua@gmail.com"><span>{% if request.session.lang == "uk" %} Написати{% elif request.session.lang == "ru" %}Написать {% else %} Write {% endif %} :</span> tokyo.od.ua@gmail.com</a>
            </div>
        </div>
    </div>
    <!--header-top end -->
    <div class="header-inner fl-wrap">
        <div class="container">
            <div class="header-container fl-wrap">
                <a href="{% url  'core:menu' %}" class="logo-holder ajax"><img src='{% static "images/logo.png" %}' alt="" /></a>
                {% comment %}
                <div class="show-reserv_button show-rb"><span>Reservation</span> <i class="fal fa-bookmark"></i></div>
                {% endcomment %}
                <div class="show-share-btn htact"><a href="https://instagram.com/tokyo.od.ua?igshid=o5y4xnlsjtwo" target="_blank"><i class="fab fa-instagram"></i></a></div>
                <div class="show-share-btn htact"><a href="https://www.facebook.com/tokyo.od.ua/" target="_blank"><i class="fab fa-facebook"></i></a></div>
                <div class="show-cart sc_btn htact"><i class="fal fa-shopping-bag"></i><span class="show-cart_count">{{ request|cart_item_count }}</span><span class="header-tooltip">{% if request.session.lang == "uk" %} Ваш кошик {% elif request.session.lang == "ru" %}Ваша корзина {% else %} Your cart {% endif %}</span></div>
                <!-- nav-button-wrap-->
                <div class="nav-button-wrap">
                    <div class="nav-button"><span></span><span></span><span></span></div>
                </div>
                <!-- nav-button-wrap end-->
                <!--  navigation -->
                <div class="nav-holder main-menu">
                    <nav>
                        <ul>
                            <li>
                                <!-- <a href="#">Home <i class="fas fa-caret-down"></i></a>
                                second level 
                                <ul>
                                    <li><a href="index.html">Parallax Image</a></li>
                                    <li><a href="index2.html">Slider</a></li>
                                    <li><a href="index3.html">Carousel</a></li>
                                    <li><a href="index4.html">Slideshow</a></li>
                                    <li><a href="index5.html">Video</a></li>
                                    <li><a href="onepage.html">One Page</a></li>
                                </ul> -->
                                {% comment %}
                                <a id="menu" href="{% url  'core:home-view' %}">{% if request.session.lang == "uk" %} Меню {% else %} Menu {% endif %}</a>
                                {% endcomment %}
                                <!--second level end-->
                            </li>
                            <li>
                                <a id="menu" href="{% url  'core:menu' %}">{% if request.session.lang == "uk" %} Меню {% elif request.session.lang == "ru" %} Меню {% else %} Menu {% endif %} {% comment %}
                                    <i class="fas fa-caret-down"></i>
                                    {% endcomment %}
                                </a>
                                <!-- <ul>
                                    <li><a href="menu3.html">Menu 3</a></li>
                                    <li><a href="menu3.html">Menu 3</a></li>
                                    <li><a href="menu3.html">Menu 3</a></li>
                                    <li><a href="menu3.html">Menu 3</a></li>
                                    <li><a href="menu3.html">Menu 3</a></li>
                                    <li><a href="menu3.html">Menu 3</a></li>
                                </ul> -->
                                <!-- second level end -->
                                <!-- <a href="{% url  'core:menu' %}">Меню</a> -->
                            </li>
                            <li><a id="propositions" href="{% url  'proposition:all_prospositions' %}" class="act-link">{% if request.session.lang == "uk" %} Акції {% elif request.session.lang == "ru" %} Акции {% else %} Promotions {% endif %}</a></li>
                            <li><a id="delivery" href="{% url  'core:delivery' %}" class="act-link">{% if request.session.lang == "uk" %} Доставка та оплата {% elif request.session.lang == "ru" %} Доставка и оплата {% else %} Order and Payment {% endif %}</a></li>
                            <!-- <li><a id="shop" href="{% url  'core:shop' %}">{% if request.session.lang == "uk" %} Пошук по компонентам {% elif request.session.lang == "ru" %} Поиск по компонентам {% else %} Search by components {% endif %}</a></li> -->
                            {% comment %}
                            <li>
                                <a href="#">Pages<i class="fas fa-caret-down"></i></a>
                                <!--second level -->
                                <ul>
                                    <li><a href="{% url  'core:shop' %}">Shop</a></li>
                                    <li><a href="product-single.html">Product Single</a></li>
                                    <li><a href="cart.html">Cart</a></li>
                                    <li><a href="gallery.html">Gallery</a></li>
                                    <li><a href="blog-single.html">Blog single</a></li>
                                    <li><a href="404.html">404</a></li>
                                    <li><a href="coming-soon.html">Coming Soon</a></li>
                                </ul>
                                <!--second level end-->
                            </li>
                            {% endcomment %}
                        </ul>
                    </nav>
                </div>
                <!-- navigation  end -->
                <!-- header-cart_wrap  -->
                <div class="header-cart_wrap novis_cart">
                    <div class="header-cart_title">{% if request.session.lang == "uk" %} Ваш кошик {% elif request.session.lang == "ru" %} Ваша корзина {% else %} Your cart {% endif %} <span>{{ request|cart_item_count }} {% if request.session.lang == "uk" %} товарів {% elif request.session.lang == "ru" %} товаров {% else %} products {% endif %}</span></div>
                    <div class="header-cart_wrap_container fl-wrap">
                        <div class="box-widget-content">
                            <div class="widget-posts fl-wrap">
                                <ol>
                                    {% if request|cart_items %} {% for item in request|cart_items %}
                                    <li class="clearfix">
                                        <a href="#" class="widget-posts-img"><img src="{{ item.item.image.url }}" class="respimg" alt="" /></a>
                                        <div class="widget-posts-descr">
                                            <a href="{{ item.item.get_absolute_url }}" title="">
                                            {% if request.session.lang == "uk" %} 
                                              {{ item.item.title }}
                                            {% elif request.session.lang == "ru" %}
                                              {{ item.item.title_ru }}
                                            {% else %}
                                              {{ item.item.title_eng }}
                                            {% endif %}
                                            </a>
                                            <div class="widget-posts-descr_calc clearfix">
                                                {{ item.quantity }} <span>x</span>
                                                {% if item.item.discount_price %} ₴{{ item.item.discount_price }} {% else %} ₴{{ item.item.price }} {% endif %}
                                            </div>
                                        </div>
                                        <a href="{{ item.item.get_remove_from_cart_url }}" class="clear-cart_button"><i class="fal fa-times"></i></a>
                                    </li>
                                    {% endfor %} {% endif %}
                                </ol>
                            </div>
                        </div>
                    </div>
                    <div class="header-cart_wrap_total fl-wrap">
                        <div class="header-cart_wrap_total_item">{% if request.session.lang == "uk" %} Підсумок {% elif request.session.lang == "ru" %} Итого {% else %} Total {% endif %} : <span>₴{{ request|total_order }}</span></div>
                    </div>
                    <div class="header-cart_wrap_footer fl-wrap">
                        <a href="{% url  'core:order-summary' %}">{% if request.session.lang == "uk" %} Переглянути кошик {% elif request.session.lang == "ru" %} Просмотреть корзину {% else %} View cart {% endif %}</a>
                        <a href="{% url  'core:checkout' %}">{% if request.session.lang == "uk" %} Розрахунок {% elif request.session.lang == "ru" %} Рассчитаться {% else %} Checkout {% endif %}</a>
                    </div>
                </div>
                <!-- header-cart_wrap end  -->
                <!-- share-wrapper -->
                <div class="share-wrapper isShare">
                    <div class="share-container fl-wrap"></div>
                </div>
                <!-- share-wrapper-end -->
            </div>
        </div>
    </div>
    <!-- header-inner end  -->
</header>

templates/loader.html
<div class="loader-wrap">
    <div class="loader-item">
        <div class="cd-loader-layer" data-frame="25">
            <div class="loader-layer"></div>
        </div>
        <span class="loader"></span>
    </div>
</div>